ALTER TABLE public.glpi_plugin_integaglpi_configs
  ADD COLUMN IF NOT EXISTS ai_supervisor_enabled TEXT NULL,
  ADD COLUMN IF NOT EXISTS ai_supervisor_provider TEXT NULL,
  ADD COLUMN IF NOT EXISTS ai_supervisor_model TEXT NULL,
  ADD COLUMN IF NOT EXISTS ai_supervisor_timeout_seconds INTEGER NULL,
  ADD COLUMN IF NOT EXISTS ai_supervisor_max_messages INTEGER NULL,
  ADD COLUMN IF NOT EXISTS ai_supervisor_max_chars INTEGER NULL,
  ADD COLUMN IF NOT EXISTS ai_supervisor_dry_run TEXT NULL,
  ADD COLUMN IF NOT EXISTS copilot_enabled TEXT NULL,
  ADD COLUMN IF NOT EXISTS copilot_provider TEXT NULL,
  ADD COLUMN IF NOT EXISTS copilot_model TEXT NULL,
  ADD COLUMN IF NOT EXISTS copilot_dry_run TEXT NULL,
  ADD COLUMN IF NOT EXISTS copilot_timeout_ms INTEGER NULL,
  ADD COLUMN IF NOT EXISTS copilot_max_context_messages INTEGER NULL,
  ADD COLUMN IF NOT EXISTS copilot_max_context_chars INTEGER NULL,
  ADD COLUMN IF NOT EXISTS external_research_enabled TEXT NULL,
  ADD COLUMN IF NOT EXISTS external_research_cloud_enabled TEXT NULL,
  ADD COLUMN IF NOT EXISTS external_research_rate_limit_per_day INTEGER NULL,
  ADD COLUMN IF NOT EXISTS p4_candidate_review_enabled TEXT NULL,
  ADD COLUMN IF NOT EXISTS p4_candidate_review_provider TEXT NULL,
  ADD COLUMN IF NOT EXISTS p4_candidate_review_model TEXT NULL,
  ADD COLUMN IF NOT EXISTS p4_confidence_threshold INTEGER NULL,
  ADD COLUMN IF NOT EXISTS p4_max_candidates_per_run INTEGER NULL,
  ADD COLUMN IF NOT EXISTS embeddings_enabled TEXT NULL,
  ADD COLUMN IF NOT EXISTS cloud_dpo_approved TEXT NULL,
  ADD COLUMN IF NOT EXISTS cloud_director_approved TEXT NULL,
  ADD COLUMN IF NOT EXISTS cloud_admin_opt_in TEXT NULL,
  ADD COLUMN IF NOT EXISTS cloud_budget_configured TEXT NULL,
  ADD COLUMN IF NOT EXISTS cloud_incident_ack TEXT NULL,
  ADD COLUMN IF NOT EXISTS cloud_synthetic_test_ok TEXT NULL,
  ADD COLUMN IF NOT EXISTS ai_settings_updated_by BIGINT NULL;

INSERT INTO public.glpi_plugin_integaglpi_configs (
  context,
  ai_supervisor_enabled,
  ai_supervisor_provider,
  ai_supervisor_dry_run,
  copilot_enabled,
  copilot_provider,
  copilot_dry_run,
  external_research_enabled,
  external_research_cloud_enabled,
  p4_candidate_review_enabled,
  p4_candidate_review_provider,
  embeddings_enabled,
  cloud_dpo_approved,
  cloud_director_approved,
  cloud_admin_opt_in,
  cloud_budget_configured,
  cloud_incident_ack,
  cloud_synthetic_test_ok
) VALUES (
  'ai_settings',
  'false',
  'disabled',
  'true',
  'false',
  'disabled',
  'true',
  'false',
  'false',
  'false',
  'disabled',
  'false',
  'false',
  'false',
  'false',
  'false',
  'false',
  'false'
)
ON CONFLICT (context) DO NOTHING;

CREATE INDEX IF NOT EXISTS glpi_intega_configs_ai_settings_updated_idx
  ON public.glpi_plugin_integaglpi_configs (context, updated_at DESC)
  WHERE context = 'ai_settings';
