import { readFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const testsDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(testsDir, '../..');

async function readProjectFile(path: string): Promise<string> {
  return await readFile(resolve(repoRoot, path), 'utf8');
}

describe('PHP internal Copilot static safety', () => {
  it('keeps the Copilot endpoint permissioned, CSRF protected and away from WhatsApp sending', async () => {
    const front = await readProjectFile('integaglpi/front/copilot.draft.php');
    const client = await readProjectFile('integaglpi/src/Service/CopilotDraftClient.php');
    const ticketTab = await readProjectFile('integaglpi/templates/ticket_tab.php');
    const contextService = await readProjectFile('integaglpi/src/Service/TicketContextService.php');
    const env = await readProjectFile('integration-service/src/config/env.ts');
    const dependencies = await readProjectFile('integration-service/src/buildDependencies.ts');

    expect(front).toContain('Session::checkLoginUser();');
    expect(front).toContain('Plugin::canUpdate()');
    expect(front).toContain('Plugin::isCsrfValid($_POST)');
    expect(front).toContain("($_GET['csrf_token'] ?? '') === '1'");
    expect(front).toContain("$payload['csrf_token'] = Plugin::getCsrfToken()");
    expect(front).toContain('csrf_denied');
    expect(front).toContain('Sessão/token expirado. Recarregue a página e tente novamente.');
    expect(front).toContain('error_type');
    expect(front).toContain('integaglpiCopilotUserMessage');
    expect(front).toContain('O Copiloto demorou mais que o esperado');
    expect(front).toContain('Serviço de IA indisponível no momento');
    expect(front).toContain('A IA respondeu em formato inválido');
    expect(front).toContain('A IA retornou um rascunho sem checklist técnico obrigatório');
    expect(front).toContain('buildCopilotContext');
    expect(client).toContain('/internal/glpi/copilot/draft');
    expect(client).toContain('COPILOT_DRAFT_TIMEOUT_MS = 8000');
    expect(front).toContain('session_write_close();');
    expect(front).toContain('createDraftJob');
    expect(front).toContain('getDraftJobStatus');
    expect(client).toContain("$payload['action'] = 'generate_async';");
    expect(client).toContain("$payload['action'] = 'status';");
    expect(client).toContain('effectiveCopilotRuntimeConfig');
    expect(client).toContain('runtime_config');
    expect(client).toContain('copilot_model');
    expect(client).toContain('copilot_timeout_ms');
    expect(client).toContain('CURLOPT_TIMEOUT_MS');
    expect(client).toContain('payload_size');
    expect(client).not.toMatch(/__construct\s*\(\s*(?:public|protected|private)\s/i);
    expect(client).not.toMatch(/\breadonly\b/i);
    expect(client).not.toContain('CURLOPT_TIMEOUT        => 35');
    expect(ticketTab).toContain('Assistente IA');
    expect(ticketTab).toContain('Base de Conhecimento Local');
    expect(ticketTab).toContain('Consultar KB Local');
    expect(ticketTab).toContain('Gerar rascunho com IA');
    expect(ticketTab).toContain('Provider efetivo:');
    expect(ticketTab).toContain('Rascunho técnico:');
    expect(ticketTab).toContain('origin_label');
    expect(ticketTab).toContain('Pesquisar fora');
    expect(ticketTab).toContain('Sugerir resposta');
    expect(ticketTab).toContain("payload.set('copilot_action', 'status')");
    expect(ticketTab).toContain('Gerando rascunho em segundo plano');
    expect(ticketTab).toContain('pollCopilotDraft');
    expect(ticketTab).toContain('refreshCsrfToken');
    expect(ticketTab).toContain('updateCsrfToken');
    expect(ticketTab).toContain('isCsrfFailure');
    expect(ticketTab).toContain('copilotMessage');
    expect(ticketTab).toContain('Rascunho gerado por IA. Revise antes de enviar. Nenhuma mensagem é enviada automaticamente.');
    expect(ticketTab).toContain('Usar rascunho');
    expect(ticketTab).toContain('Copiar rascunho');
    expect(ticketTab).toContain('Pesquisa externa controlada');
    expect(ticketTab).toContain('getExternalResearchUrl');
    expect(ticketTab).toContain('canExternalResearchRead');
    expect(ticketTab).not.toContain("payload.set('copilot_action', 'use')");
    expect(contextService).toContain('NativeKnowledgeBaseService');
    expect(contextService).toContain('buildTicketAiAssistant');
    expect(contextService).toContain('copilot_provider');
    expect(contextService).toContain('copilot_model');
    expect(contextService).toContain('origin_label');
    expect(contextService).toContain('TICKET_AI_ASSISTANT_KB_LOCAL_PREPARED');
    expect(contextService).toContain('glpi_plugin_integaglpi_kb_candidates');
    expect(contextService).toContain('glpi_plugin_integaglpi_hist_insights');
    expect(contextService).toContain('COPILOT_MAX_MESSAGES = 8');
    expect(contextService).toContain('COPILOT_MESSAGE_CHARS = 360');
    expect(contextService).toContain('COPILOT_MAX_KB_ARTICLES = 3');
    expect(contextService).toContain('buildExternalResearchTicketSummary');
    expect(contextService).toContain('sanitizeExternalResearchPrefillText');
    expect(contextService).toContain('empresa: [empresa]');
    expect(contextService).toContain('nome: [nome]');
    expect(contextService).toContain('[dominio]');
    expect(contextService).toContain('[id]');
    expect(contextService).toContain('[midia]');
    expect(env).toContain('COPILOT_DRAFT_MODEL');
    expect(env).toContain('COPILOT_TIMEOUT_SECONDS');
    expect(dependencies).toContain('copilotDraftModel');
    expect(dependencies).toContain('copilotTimeoutSeconds');
    expect(dependencies).toContain('env.COPILOT_DRAFT_MODEL.trim()');
    expect(dependencies).toContain('env.COPILOT_TIMEOUT_SECONDS > 0');

    const combined = `${front}\n${client}\n${ticketTab}\n${contextService}`;
    expect(combined).not.toMatch(/MetaClient|sendOutbound|sendTemplate|ticket\.whatsapp\.reply\.php.*copilot|KnowbaseItem::add|Publicar automaticamente|match \(|readonly|__construct\s*\(\s*(?:public|protected|private)\s/i);
  });
});
