/**
 * KbSearchPlannerService — Deterministic search plan generator for KB RAG.
 *
 * Generates a controlled SearchPlan before every KB search, replacing ad-hoc
 * filter accumulation with a structured, auditable plan. The plan specifies:
 *   - normalizedQuery (PII-free, de-accented)
 *   - intent (semantic category)
 *   - productOrSystem (from product anchors)
 *   - mustTerms, boostTerms, negativeTerms, negativeDomains
 *   - sourceTiersAllowed
 *   - minimumConfidence (threshold — KB_INSUFFICIENT if not met after ranking)
 *
 * Flow:
 *   1. Normalize and PII-guard the query.
 *   2. Detect product/system via product anchors (deterministic).
 *   3. Detect intent via pattern matching.
 *   4. Build SearchPlan from anchor or generic template.
 *   5. Validate: remove forbidden fields (raw_sql, sql_query, executable_command).
 *   6. Optional: local AI enrichment (placeholder — deterministic only for phase 1).
 *
 * Source tiers:
 *   tier_1_product_specific (0.60) — articles for a named product anchor
 *   tier_2_operational_kb   (0.70) — operational/generic KB
 *   tier_3_generic_playbook (0.85) — catch-all generic playbooks
 *   tier_4_automation       (0.95) — automation scripts (rarely searched)
 *
 * Invariants:
 *   - Deterministic first. Local AI is optional enrichment.
 *   - NO cloud AI (structurally absent).
 *   - NO SQL generated by AI.
 *   - NO command execution.
 *   - NO MariaDB access.
 *   - PII-free normalizedQuery at all times.
 *
 * Phase: integaglpi_kb_rag_ai_search_planner_hybrid_retrieval_001
 */

// ── Types ─────────────────────────────────────────────────────────────────────

export type Intent =
  | 'application_not_opening'
  | 'identity_sync'
  | 'backup_restore'
  | 'server_slow'
  | 'network_issue'
  | 'license_activation'
  | 'generic';

export type SourceTier =
  | 'tier_1_product_specific'
  | 'tier_2_operational_kb'
  | 'tier_3_generic_playbook'
  | 'tier_4_automation';

export const ALL_SOURCE_TIERS: readonly SourceTier[] = [
  'tier_1_product_specific',
  'tier_2_operational_kb',
  'tier_3_generic_playbook',
  'tier_4_automation',
];

/** Fields that must never appear in a SearchPlan (safety gate). */
export const FORBIDDEN_PLAN_FIELDS = [
  'raw_sql',
  'sql_query',
  'executable_command',
  'customer_response',
] as const;

export interface SearchPlan {
  readonly normalizedQuery: string;
  readonly intent: Intent;
  readonly productOrSystem: string | null;
  readonly domain: string | null;
  readonly symptoms: string[];
  readonly mustTerms: string[];
  readonly boostTerms: string[];
  readonly negativeTerms: string[];
  readonly negativeDomains: string[];
  readonly sourceTiersAllowed: SourceTier[];
  readonly minimumConfidence: number;
  readonly topK: number;
  readonly reason: string;
  readonly planSource: 'deterministic' | 'local_ai';
}

// ── Product Anchors ───────────────────────────────────────────────────────────

interface ProductAnchor {
  readonly name: string;
  readonly aliases: readonly string[];
  readonly domain: string;
  readonly mustTerms: readonly string[];
  readonly boostTerms: readonly string[];
  readonly negativeTerms: readonly string[];
  readonly negativeDomains: readonly string[];
  readonly sourceTier: SourceTier;
  readonly minimumConfidence: number;
  readonly topK: number;
}

const PRODUCT_ANCHORS: readonly ProductAnchor[] = [
  {
    name: 'Micromed',
    aliases: ['micromed', 'smarthealth'],
    domain: 'application',
    mustTerms: ['micromed'],
    boostTerms: ['proxy', 'smarthealth', 'acesso', 'erro', 'dbrest'],
    negativeTerms: ['ativacao', 'slmgr', 'licenca windows', 'kms'],
    negativeDomains: ['windows_activation', 'm365_license'],
    sourceTier: 'tier_1_product_specific',
    minimumConfidence: 0.60,
    topK: 3,
  },
  {
    name: 'Active Directory',
    aliases: ['active directory', 'ad connect', 'azure ad connect', 'entra id'],
    domain: 'identity_cloud',
    mustTerms: ['ad', 'active directory', 'azure ad', 'sincron', 'sync'],
    boostTerms: ['azure', 'source of authority', 'sincronizacao', 'delta', 'connect'],
    negativeTerms: ['slmgr', 'licenca windows', 'ativacao windows', 'micromed'],
    negativeDomains: ['windows_activation', 'micromed'],
    sourceTier: 'tier_1_product_specific',
    minimumConfidence: 0.60,
    topK: 3,
  },
  {
    name: 'Synology',
    aliases: ['synology', 'active backup for business'],
    domain: 'backup',
    mustTerms: ['synology'],
    boostTerms: ['restore', 'arquivo', 'backup', 'granular', 'recovery'],
    negativeTerms: [],
    negativeDomains: ['windows_activation', 'micromed'],
    sourceTier: 'tier_1_product_specific',
    minimumConfidence: 0.60,
    topK: 3,
  },
  {
    name: 'Microsoft 365',
    aliases: ['m365', 'microsoft 365', 'office 365', 'exchange online'],
    domain: 'cloud',
    mustTerms: [],
    boostTerms: ['licenca', 'exchange', 'retencao', 'mailbox', 'admin center'],
    negativeTerms: [],
    negativeDomains: [],
    sourceTier: 'tier_1_product_specific',
    minimumConfidence: 0.60,
    topK: 3,
  },
  {
    name: 'Backup',
    aliases: ['backup', 'restore', 'bkp'],
    domain: 'backup',
    mustTerms: [],
    boostTerms: ['arquivo em uso', 'restore', 'validacao', 'incremental', 'job', 'agente'],
    negativeTerms: [],
    negativeDomains: ['windows_activation'],
    sourceTier: 'tier_2_operational_kb',
    minimumConfidence: 0.70,
    topK: 5,
  },
  {
    name: 'Firewall / Proxy',
    aliases: ['firewall', 'proxy', 'pfsense'],
    domain: 'network',
    mustTerms: [],
    boostTerms: ['porta', 'bloqueio', 'timeout', 'api', 'localhost', 'pfsense', 'regra'],
    negativeTerms: [],
    negativeDomains: [],
    sourceTier: 'tier_2_operational_kb',
    minimumConfidence: 0.70,
    topK: 5,
  },
];

/**
 * Lowercase product names for article tier computation in KbRankingService.
 * Exported so KbRankingService can classify articles without importing PRODUCT_ANCHORS directly.
 */
export const PRODUCT_ANCHOR_NAMES: readonly string[] = PRODUCT_ANCHORS.map(
  (a) => a.name.toLowerCase(),
);

// ── Negative domain detection patterns ───────────────────────────────────────

/**
 * Maps abstract negative-domain labels → regex patterns for KB article text.
 * Used by KbRankingService.hasDomainConflict() for plan-based exclusion.
 * Exported for use in KbRankingService.
 */
export const NEGATIVE_DOMAIN_PATTERNS: Readonly<Record<string, RegExp>> = {
  windows_activation: /\b(ativacao|ativar|ativa|licenca|license)\b/,
  m365_license: /\b(m365|microsoft 365|office 365|licen[cç]a microsoft)\b/,
  micromed: /\bmicromed\b/,
  identity_cloud: /\b(active directory|azure ad|entra)\b/,
  backup: /\b(backup|restore|bkp)\b/,
  network: /\b(firewall|proxy|rede)\b/,
};

// ── Intent detection ──────────────────────────────────────────────────────────

const INTENT_PATTERNS: ReadonlyArray<{ intent: Intent; patterns: readonly RegExp[] }> = [
  {
    intent: 'application_not_opening',
    patterns: [
      /nao\s+(abre|inicia|conecta|acessa|carrega|funciona)/,
      /\b(abrindo|iniciando|carregando)\b/,
      /\b(nao esta abrindo|nao abre|sistema parado|aplicativo travado)\b/,
    ],
  },
  {
    intent: 'identity_sync',
    patterns: [
      /\b(sincronizando|sync|sincronizacao|sincronizar)\b/,
      /\b(active directory|azure ad|ad connect|entra id)\b/,
    ],
  },
  {
    intent: 'backup_restore',
    patterns: [
      /\b(backup|restore|restaurar|recuperar|bkp)\b/,
      /\b(arquivo em uso|arquivo.*nao.*encontrado)\b/,
    ],
  },
  {
    intent: 'server_slow',
    patterns: [
      /\b(lento|devagar|travado|demora|alto consumo)\b/,
      /\b(cpu|memoria|disco)\b.{0,20}\b(alta|alto|cheio|sobrecarregado)\b/,
    ],
  },
  {
    intent: 'network_issue',
    patterns: [
      /\b(sem conexao|nao acessa internet|rede|vpn|firewall|proxy)\b/,
      /\b(bloqueado|timeout|sem acesso|erro de conexao)\b/,
    ],
  },
  {
    intent: 'license_activation',
    patterns: [
      /\b(ativacao|ativar|licenca|kms|slmgr)\b/,
      /\b(windows.*ativacao|microsoft.*licenca)\b/,
    ],
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

/** PII guard (inlined to avoid circular dep with KbRagCopilotService). */
const PLAN_PII_PATTERNS: Array<[RegExp, string]> = [
  [/(?:\+55\s*)?(?:\(?\d{2}\)?\s*)?\d{4,5}[\s.-]?\d{4}\b/g, ''],
  [/\b[\w.+-]+@[\w-]+\.[\w.]+\b/gi, ''],
  [/\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b/g, ''],
  [/\b\d{2}\.?\d{3}\.?\d{3}[/\\]?\d{4}-?\d{2}\b/g, ''],
  [/(?:token|senha|password|secret|api[_-]?key|bearer)\s*[:=]?\s*["']?\S{8,}["']?/gi, ''],
];

function guardPii(text: string): string {
  let result = text;
  for (const [pattern, replacement] of PLAN_PII_PATTERNS) {
    result = result.replace(pattern, replacement);
  }
  return result;
}

/** Normalize for anchor matching: PII-free, lowercase, de-accented, whitespace-collapsed. */
export function normalizeForPlan(text: string): string {
  return guardPii(String(text ?? ''))
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^\w\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 400);
}

function detectAnchor(normalizedQuery: string): ProductAnchor | null {
  for (const anchor of PRODUCT_ANCHORS) {
    for (const alias of anchor.aliases) {
      const normalizedAlias = alias
        .toLowerCase()
        .normalize('NFD')
        .replace(/[̀-ͯ]/g, '');
      if (normalizedQuery.includes(normalizedAlias)) {
        return anchor;
      }
    }
  }
  return null;
}

function detectIntent(query: string): Intent {
  // Run on de-accented lowercase for consistent matching
  const normalized = query
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '');

  for (const { intent, patterns } of INTENT_PATTERNS) {
    if (patterns.some((p) => p.test(normalized))) {
      return intent;
    }
  }
  return 'generic';
}

/** Strip forbidden fields from a plan object (runtime safety gate). */
function validatePlan(plan: SearchPlan): SearchPlan {
  const obj = plan as unknown as Record<string, unknown>;
  for (const field of FORBIDDEN_PLAN_FIELDS) {
    if (Object.prototype.hasOwnProperty.call(obj, field)) {
      // eslint-disable-next-line @typescript-eslint/no-dynamic-delete
      delete obj[field];
    }
  }
  return plan;
}

// ── Service ───────────────────────────────────────────────────────────────────

export interface KbPlanClientContext {
  productOrSystem?: string | null;
  category?: string | null;
}

export class KbSearchPlannerService {
  /**
   * @param _ollamaPort Reserved for future local AI enrichment — pass null for
   *                    deterministic-only mode. Cloud AI is structurally absent.
   */
  public constructor(
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    private readonly _ollamaPort: { generateText(prompt: string): Promise<string> } | null = null,
  ) {}

  /**
   * Build a SearchPlan for the given query.
   *
   * @param query        Raw query (PII guard applied internally).
   * @param clientContext Optional client context (product hint).
   */
  public async buildPlan(
    query: string,
    clientContext?: KbPlanClientContext | null,
  ): Promise<SearchPlan> {
    const normalizedQuery = normalizeForPlan(String(query ?? '').trim());
    const anchor = detectAnchor(normalizedQuery);
    const intent = detectIntent(query);

    let plan: SearchPlan;

    if (anchor !== null) {
      plan = this.buildAnchoredPlan(normalizedQuery, anchor, intent);
    } else if (clientContext?.productOrSystem) {
      // Try to resolve product hint to an anchor
      const ctxNorm = normalizeForPlan(clientContext.productOrSystem);
      const ctxAnchor = PRODUCT_ANCHORS.find((a) =>
        a.aliases.some((al) => {
          const normalizedAlias = al.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
          return ctxNorm.includes(normalizedAlias) || normalizedAlias.includes(ctxNorm);
        }),
      ) ?? null;

      plan = ctxAnchor !== null
        ? this.buildAnchoredPlan(normalizedQuery, ctxAnchor, intent)
        : this.buildGenericPlan(normalizedQuery, intent, clientContext);
    } else {
      plan = this.buildGenericPlan(normalizedQuery, intent, clientContext);
    }

    return validatePlan(plan);
  }

  private buildAnchoredPlan(
    normalizedQuery: string,
    anchor: ProductAnchor,
    intent: Intent,
  ): SearchPlan {
    return {
      normalizedQuery,
      intent,
      productOrSystem: anchor.name,
      domain: anchor.domain,
      symptoms: [],
      mustTerms: [...anchor.mustTerms],
      boostTerms: [...anchor.boostTerms],
      negativeTerms: [...anchor.negativeTerms],
      negativeDomains: [...anchor.negativeDomains],
      sourceTiersAllowed: [anchor.sourceTier, 'tier_2_operational_kb'],
      minimumConfidence: anchor.minimumConfidence,
      topK: anchor.topK,
      reason: `Product anchor: ${anchor.name} (domain: ${anchor.domain})`,
      planSource: 'deterministic',
    };
  }

  private buildGenericPlan(
    normalizedQuery: string,
    intent: Intent,
    clientContext?: KbPlanClientContext | null,
  ): SearchPlan {
    const tokenCount = normalizedQuery
      .split(/\s+/)
      .filter((t) => t.length >= 3).length;
    const isVeryGeneric = tokenCount <= 2;

    return {
      normalizedQuery,
      intent,
      productOrSystem: clientContext?.productOrSystem ?? null,
      domain: null,
      symptoms: [],
      mustTerms: [],
      boostTerms: [],
      negativeTerms: [],
      negativeDomains: [],
      sourceTiersAllowed: [
        'tier_1_product_specific',
        'tier_2_operational_kb',
        'tier_3_generic_playbook',
      ],
      minimumConfidence: isVeryGeneric ? 0.80 : 0.70,
      topK: 5,
      reason: isVeryGeneric
        ? 'Very generic query — elevated confidence threshold'
        : 'No product anchor detected — generic search',
      planSource: 'deterministic',
    };
  }
}
